controllers/PositionsController.php
<?php

namespace app\controllers;

use yii\web\Controller;

/**
 * 统战阵地
 *
 * @author hiscaler <hiscaler@gmail.com>
 */
class PositionsController extends Controller
{

    public function actionIndex($by = null, $value = null)
    {
        if (!empty($by)) {
            $by = trim($by);
            if (!in_array($by, ['area', 'category']) || empty($value)) {
                $by = 'area';
            }
            if ($by == 'area') {
                return $this->render('area', [
                        'items' => [
                            'province' => '省级四同创建点',
                            'city' => '市级四同创建点',
                            'county' => '县级四同创建点',
                        ],
                ]);
            } else {
                $value = trim($value);
                switch ($value) {
                    case 'province':
                        $items = [
                            1 => '同心园区',
                            4 => '同心项目',
                            7 => '同心社区',
                            10 => '同心乡村',
                        ];
                        break;
                    case 'city':
                        $items = [
                            2 => '同心园区',
                            5 => '同心项目',
                            8 => '同心社区',
                            11 => '同心乡村',
                        ];
                        break;

                    default:
                        $items = [
                            3 => '同心园区',
                            6 => '同心项目',
                            9 => '同心社区',
                            12 => '同心乡村',
                        ];
                }

                return $this->render('category', [
                        'items' => $items,
                ]);
            }
        }

        return $this->render('index');
    }

}

views/positions/area.php
<?php

use yii\helpers\Url;

$baseUrl = Yii::$app->getRequest()->getBaseUrl()
?>

<div class="page__bd_spacing page__bd_vertical_spacing">

    <div id="positions">
        <div class="weui-grids">
            <?php foreach ($items as $key => $value): ?>
                <a href="<?= Url::toRoute(['positions/index', 'by' => 'category', 'value' => $key]) ?>" class="weui-grid">
                    <div class="weui-grid__icon">
                        <img src="<?= $baseUrl ?>/images/icon-tong-xin-<?= $key ?>.png" alt="">
                    </div>
                    <p class="weui-grid__label"><?= $value ?></p>
                </a>
            <?php endforeach; ?>
        </div>
    </div>

</div>

views/positions/category.php
<?php

use yii\helpers\Url;

$baseUrl = Yii::$app->getRequest()->getBaseUrl()
?>

<div class="page__bd_spacing page__bd_vertical_spacing">

    <div id="positions">
        <div class="weui-grids">
            <?php foreach ($items as $key => $value): ?>
                <a href="<?= Url::toRoute(['demonstration-plots-tong-xin/index', 'category' => $key]) ?>" class="weui-grid">
                    <div class="weui-grid__icon">
                        <img src="<?= $baseUrl ?>/images/icon-tong-xin-<?= $key ?>.png" alt="">
                    </div>
                    <p class="weui-grid__label"><?= $value ?></p>
                </a>
            <?php endforeach; ?>
        </div>
    </div>

</div>

views/positions/index.php
<?php

use yii\helpers\Url;

$baseUrl = Yii::$app->getRequest()->getBaseUrl()
?>


<div class="page__bd_spacing page__bd_vertical_spacing">

    <div id="positions">
        <div class="weui-grids">
            <a href="<?= Url::toRoute(['positions/index', 'by' => 'area']) ?>" class="weui-grid">
                <div class="weui-grid__icon">
                    <img src="<?= $baseUrl ?>/images/icon-tong-xin.png" alt="">
                </div>
                <p class="weui-grid__label">四同创建点</p>
            </a>
            <a href="<?= Url::toRoute(['demonstration-plots-1035/index']) ?>" class="weui-grid">
                <div class="weui-grid__icon">
                    <img src="<?= $baseUrl ?>/images/icon-1035.png" alt="">
                </div>
                <p class="weui-grid__label">凝心聚力十三五行动示范点</p>
            </a>
            <a href="<?= Url::toRoute(['group-organizations/index']) ?>" class="weui-grid">
                <div class="weui-grid__icon">
                    <img src="<?= $baseUrl ?>/images/icon-group-organization.png" alt="">
                </div>
                <p class="weui-grid__label">统战团体组织</p>
            </a>
            <a href="<?= Url::toRoute(['business-organizations/index']) ?>" class="weui-grid">
                <div class="weui-grid__icon">
                    <img src="<?= $baseUrl ?>/images/icon-business-organization.png" alt="">
                </div>
                <p class="weui-grid__label">商会组织</p>
            </a>
            <a href="<?= Url::toRoute(['religion-activity-places/index']) ?>" class="weui-grid">
                <div class="weui-grid__icon">
                    <img src="<?= $baseUrl ?>/images/icon-religion-activity-place.png" alt="">
                </div>
                <p class="weui-grid__label">宗教活动场所</p>
            </a>
            <a href="<?= Url::toRoute(['demonstration-plots-other/index']) ?>" class="weui-grid">
                <div class="weui-grid__icon">
                    <img src="<?= $baseUrl ?>/images/icon-other.png" alt="">
                </div>
                <p class="weui-grid__label">其他</p>
            </a>
        </div>
    </div>

</div>